name: johnnorris
favicon: null
layout_spectrum: 0.5856978953815997
typography_spectrum: 0.2406394649296999
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5184247889555991
  lightness: 0.04987435694783926
  saturation: 0.5044622754212469
  rhythmicContrast: 0.7334463691804558
purpose: []
